 
name: mood_tracker
description: A simple mood tracking app in Flutter.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.12.0


flutter:
  uses-material-design: true
