name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.2'  # Use latest stable Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter Doctor (Debugging Step)
        run: flutter doctor

      - name: Give Execution Permissions (Fixes Permission Errors)
        run: chmod +x gradlew

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
