name: Regenerate Android Folder

on:
  push:
    branches:
      - main

jobs:
  regenerate_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter Manually (Fix Setup Issues)
        run: |
          sudo apt-get update
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          flutter --version

      - name: Run Flutter Doctor (Debugging Step)
        run: flutter doctor

      - name: Regenerate Android folder
        run: flutter create .

      - name: Commit changes (if any)
        run: |
          git add .
          git commit -m "Recreated android folder" || echo "No changes to commit"
          git push origin main
