name: Regenerate Android Folder

on:
  push:
    branches:
      - main

jobs:
  regenerate_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter (Official Action)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.2'  # Set latest stable version

      - name: Run Flutter Doctor (Debugging Step)
        run: flutter doctor

      - name: Regenerate Android folder
        run: flutter create .

      - name: Commit changes (if any)
        run: |
 
