name: Regenerate Android Folder

on:
  push:
    branches:
      - main

jobs:
  regenerate_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Regenerate Android folder
        run: flutter create .

      - name: Commit changes (if any)
        run: |
          git add .
          git commit -m "Recreated android folder" || echo "No changes to commit"
          git push origin main
